// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    /*
           Takes a single ID or an array of IDs
           Returns a single model or an array of models accordingly
    */

    getModel: function(id) {},
    saveModel: function(id) {},
    deleteModel: function(id) {}
  };

}).call(this);
