// Generated by CoffeeScript 1.6.3
(function() {
  var mongo, mongoUri;

  mongo = require('mongodb');

  mongoUri = process.env.MONGOLAB_URI;

  module.exports = {
    query: function(query) {},
    save: function() {}
  };

}).call(this);
