// Generated by CoffeeScript 1.6.3
(function() {
  var BaseModel;

  BaseModel = (function() {
    function BaseModel(id) {
      this.id = id != null ? id : null;
      this.properties = {};
    }

    BaseModel.prototype.setProperty = function(key, value) {
      return this.properties[key] = value;
    };

    BaseModel.prototype.getProperty = function(key) {
      return this.properties[key];
    };

    BaseModel.prototype.deleteProperty = function(key) {
      return delete this.properties[key];
    };

    BaseModel.prototype.hasProperty = function(key) {
      return this.properties[key] !== null && this.properties !== void 0;
    };

    return BaseModel;

  })();

  module.exports = BaseModel;

}).call(this);
