// Generated by CoffeeScript 1.6.3
(function() {
  var BaseModel, Task,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('base');

  Task = (function(_super) {
    __extends(Task, _super);

    function Task(id) {
      Task.__super__.constructor.call(this, id);
    }

    return Task;

  })(BaseModel);

  module.exports = Task;

}).call(this);
