// Generated by CoffeeScript 1.6.3
(function() {
  var BaseModel, User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('base');

  User = (function(_super) {
    __extends(User, _super);

    function User(id) {
      User.__super__.constructor.call(this, id);
    }

    return User;

  })(BaseModel);

  module.exports = User;

}).call(this);
